<?php
declare(strict_types=1);

namespace Database\Seeders;

use App\Models\ClinicalHistoryQuestion;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClinicalHistoryQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $clinicalHistoryQuestionTable = DB::table(ClinicalHistoryQuestion::TABLE_NAME);

        $clinicalHistoryQuestionTable->insert([
            // SECTION 1 - Antecedentes Patológicos Hereditarios
            $this->buildQuestion(1, 'Madre', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(1, 'Padre', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(1, 'Hermanos', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(1, 'Hijos', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(1, 'Esposo(a)', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(1, 'Tíos', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(1, 'Abuelos/Paternos', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(1, 'Madre/Maternos', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            // SECTION 2 - Antecedentes Personales Patológicos
            $this->buildQuestion(2, 'Varicela'),
            $this->buildQuestion(2, 'Rubéola'),
            $this->buildQuestion(2, 'Sarampión'),
            $this->buildQuestion(2, 'Parotiditis'),
            $this->buildQuestion(2, 'Tosferina'),
            $this->buildQuestion(2, 'Escarlatina'),
            $this->buildQuestion(2, 'Fiebre Tifoidea'),
            $this->buildQuestion(2, 'Tuberculosis'),
            $this->buildQuestion(2, 'Parasitosis'),
            $this->buildQuestion(2, 'Hepatitis'),
            $this->buildQuestion(2, 'SIDA'),
            $this->buildQuestion(2, 'Asma'),
            $this->buildQuestion(2, 'Disfunciones endocrinas'),
            $this->buildQuestion(2, 'Hipertensión arterial'),
            $this->buildQuestion(2, 'Hipotensión arterial'),
            $this->buildQuestion(2, 'Cáncer'),
            $this->buildQuestion(2, 'Diabetes'),
            $this->buildQuestion(2, 'Neoplasias'),
            $this->buildQuestion(2, 'Epilepsia'),
            $this->buildQuestion(2, 'Malformaciones'),
            $this->buildQuestion(2, 'Enfermedades renales'),
            $this->buildQuestion(2, 'Enfermedad hemorrágica'),
            $this->buildQuestion(2, 'Coagulopatias'),
            $this->buildQuestion(2, 'Anemia'),
            $this->buildQuestion(2, 'Hepatitis'),
            $this->buildQuestion(2, 'Enf. Transm. Sex.'),
            $this->buildQuestion(2, 'Amigdalitis de repetición'),
            $this->buildQuestion(2, 'Tuberculosis'),
            $this->buildQuestion(2, 'Fiebre reumática'),
            $this->buildQuestion(2, 'Enf. Cardiovasculares'),
            $this->buildQuestion(2, 'Artritis'),
            $this->buildQuestion(2, 'Covid-19'),
            $this->buildQuestion(2, 'Traumatismos con secuelas'),
            $this->buildQuestion(2, 'Intervenciones quirúrgicas'),
            $this->buildQuestion(2, '¿Por qué le intervinieron?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Cuándo le intervinieron?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, 'Alergias A:', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Está embarazada?'),
            $this->buildQuestion(2, 'SDG', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Padece de alguna enfermedad?'),
            $this->buildQuestion(2, '¿Qué enfermedad?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Está bajo algún tratamiento médico?'),
            $this->buildQuestion(2, '¿Qué tratamiento médico?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Qué medicamento/s consume habitualmente?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Qué medicamento/s ha consumido en los últimos 5 años?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Realiza algún deporte?'),
            $this->buildQuestion(2, '¿Nota algún malestar al realizarlo?'),
            $this->buildQuestion(2, '¿Es alérgico a alguna medicamento?'),
            $this->buildQuestion(2, '¿Qué medicamento/s?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Es diabético?'),
            $this->buildQuestion(2, '¿Está controlado?'),
            $this->buildQuestion(2, '¿Con qué está controlado?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Tiene algún problema cardiaco?'),
            $this->buildQuestion(2, '¿Cuá problema cardiaco?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Toma seguido aspirina y/o anticoagulante?'),
            $this->buildQuestion(2, '¿Con qué frecuencia?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Tiene presión alta?'),
            $this->buildQuestion(2, '¿Está controlado?'),
            $this->buildQuestion(2, '¿Con qué está controlado?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Tiene problemas renales?'),
            $this->buildQuestion(2, '¿Úlcera gástrica?'),
            $this->buildQuestion(2, '¿Tuvo o tiene hepatitis?'),
            $this->buildQuestion(2, '¿De que tipo de hepatitis?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Otra enfermedad infecto-contagiosa?'),
            $this->buildQuestion(2, '¿Cuál enfermedad infecto-contagiosa?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Tuvo transfusiones?'),
            $this->buildQuestion(2, '¿Porqué tuvo transfusiones?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Cuándo tuvo transfusiones?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Tiene algún problema respiratorio?'),
            $this->buildQuestion(2, '¿Cuál problema respiratorio?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Fuma?'),
            $this->buildQuestion(2, '¿Toma?'),
            $this->buildQuestion(2, '¿Hay alguna otra enfermedad o recomendación de su Médico que quiera dejar constancia?'),
            $this->buildQuestion(2, '¿Cuál otra enfermedad?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(2, '¿Realiza algún tipo de tratamiento homeopático, Acupuntura, Otros?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            //SECTION 3 - Historia Clínica Odontológica
            $this->buildQuestion(3, '¿Por que asistió a la consulta?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(3, '¿Tomó algún medicamento?'),
            $this->buildQuestion(3, '¿Nombre de los medicamentos?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(3, '¿Desde cuando?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(3, '¿Obtuvo Resultados?'),
            $this->buildQuestion(3, '¿Ha tenido dolor?  Suave  Moderado  Intenso  Temporario  Intermitente  Continuo  Espontáneo  Provocado'),
            $this->buildQuestion(3, '¿Donde tuvo el dolor?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(3, 'Irradió ¿Hacia donde?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(3, '¿Puede calmarlo con algo?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(3, '¿Sufrió algún golpe en los dientes?'),
            $this->buildQuestion(3, '¿Cuándo?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(3, '¿Cómo se produjo?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(3, '¿Se fracturó algún diente?'),
            $this->buildQuestion(3, '¿Cuál?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(3, '¿Recibió algún tratamiento?'),
            $this->buildQuestion(3, '¿Qué tratamiento?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(3, '¿Tiene dificultad para hablar?'),
            $this->buildQuestion(3, '¿Para masticar?'),
            $this->buildQuestion(3, '¿Para abrir la boca?'),
            $this->buildQuestion(3, '¿Para tragar alimentos?'),
            $this->buildQuestion(3, '¿Ha observado algo anormal en los labios?'),
            $this->buildQuestion(3, '¿Ha observado algo anormal en lengua?'),
            $this->buildQuestion(3, '¿Ha observado algo anormal en paladar?'),
            $this->buildQuestion(3, '¿Ha observado algo anormal en piso de boca?'),
            $this->buildQuestion(3, '¿Ha observado algo anormal en carrillos?'),
            $this->buildQuestion(3, '¿Ha observado algo anormal en rebordes?'),
            $this->buildQuestion(3, '¿Ha observado algo anormal en otro?'),
            // SECTION 4 - ¿Qué tipo de lesiones presenta?
            $this->buildQuestion(4, '¿Manchas?'),
            $this->buildQuestion(4, '¿Abultamiento de los tejidos?'),
            $this->buildQuestion(4, '¿Ulceraciones?'),
            $this->buildQuestion(4, '¿Ampollas?'),
            $this->buildQuestion(4, 'Otros:', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(4, '¿Le sangran las encías?'),
            $this->buildQuestion(4, '¿Cuándo?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(4, '¿Le sale pus de algún lugar se su boca?'),
            $this->buildQuestion(4, '¿De dónde?', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(4, '¿Tiene movilidad en sus dientes?'),
            $this->buildQuestion(4, '¿Al morder siente altos dientes?'),
            $this->buildQuestion(4, '¿Ha tenido la cara hinchada?'),
            $this->buildQuestion(4, '¿Se puso hielo, calor u otros?'),
            // SECTION 5 - Antecedentes Personales No Patológicos
            $this->buildQuestion(5, 'Frecuencia del cepillado', ClinicalHistoryQuestion::QUESTION_TYPE_INPUT),
            $this->buildQuestion(5, 'Utiliza hilo dental'),
            $this->buildQuestion(5, 'Le han realizado aplicación tópica de fluoruros'),
            $this->buildQuestion(5, 'Enjuagues bucal'),
        ]);
    }

    private function buildQuestion(
        int $sectionId,
        string $text,
        string $type = ClinicalHistoryQuestion::QUESTION_TYPE_YES_OR_NO,
    ): array {
        return [
            ClinicalHistoryQuestion::DB_FIELD_FK_CLINICAL_HISTORY_SECTION => $sectionId,
            ClinicalHistoryQuestion::DB_FIELD_QUESTION => $text,
            ClinicalHistoryQuestion::DB_FIELD_TYPE => $type,
        ];
    }
}
