version: '3.8'

services:
  composer:
    image: composer:latest
    entrypoint: composer
    volumes:
      - .:/app
      - composer-cache:/root/.composer/cache 

volumes:
  composer-cache:
    name: 'composer-cache'